version: "3.8"
services:
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    ports:
      - 2376:2376
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    networks:
      jenkins-network:
        aliases:
          - docker
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
    restart: unless-stopped

  jenkins:
    image: jenkinsci/blueocean
    container_name: jenkins
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-docker-certs:/certs/client:ro
      - jenkins-data:/var/jenkins_home
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - jenkins-network
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    command: --httpPort=-1 --httpsPort=8080 --httpsKeyStore=/etc/letsencrypt/live/${APACHE_SERVER_NAME}/jenkins.jks --httpsKeyStorePassword=${SSL_CERT_PASSWORD}
    depends_on:
      - jenkins-docker
    restart: unless-stopped

volumes:
  jenkins-data:
    name: jenkins-data
  jenkins-docker-certs:
    name: jenkins-docker-certs

networks:
  jenkins-network:
    name: jenkins-network
    driver: bridge
