version: "3.8"
services:
  database:
    image: mysql:latest
    container_name: ICT3x03-Database
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ict3x03-volume:/var/lib/mysql
    networks:
      - ict3x03-network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: unless-stopped

  node:
    image: node:lts-alpine
    container_name: ICT3x03-Node-Development
    volumes:
      - ./../project:/var/www/html
    networks:
      - ict3x03-network
    working_dir: /var/www/html
    command: sh -c "npm install && npm run production"
    restart: "no"

  website:
    build:
      args:
        BUILD_ENVIRONMENT: production
      context: ./website
    image: ict3x03/php:7.4-apache-production
    container_name: ICT3x03-Website
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./../project:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - ict3x03-network
    environment:
      APACHE_SERVER_NAME: ${APACHE_SERVER_NAME}
    depends_on:
      - database
      - node
    restart: unless-stopped

volumes:
  ict3x03-volume:
    name: ict3x03-volume

networks:
  ict3x03-network:
    name: ict3x03-network
    driver: bridge
